### ISSUE TITLE
PEAR mail error under PHP 7.0.8

### ISSUE THREAD

**Issue by cpinfold** [eventum/eventum#234]
@glensc - I know you are working on removing the PEAR mail code.

In the mean time, the email portion of the system doesn't work under PHP 7.0 (under 3.11 to 3.1.9) due to a reference on:
/var/www/support/vendor/pear/mail/Mail/smtp.php on line 349

````PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /path/to/eventum/vendor/pear/mail/Mail/smtp.php on line 349````

line reads:

````$this->_smtp = &new Net_SMTP($this->host,````
should read:
````$this->_smtp = new Net_SMTP($this->host,````

I'm not sure if you would like to change the code or I can make a note in the Wiki for a PHP 7 upgrade?

**Comment by glensc** [comment]
php 7 is not supported. work to replace PEAR libraries is slow work in progress.

**Comment by glensc** [comment]
you may try to send the fix to pear package itself

**Comment by cpinfold** [comment]
Thanks.

Someone beat me to fixing it in 2011.

Eventum's composer.json is requiring php/mail <1.30.  This issue is fixed in release 1.3.0 (the latest)

https://github.com/pear/Mail/blob/master/Mail/smtp.php#L346

1.3.0 only lists PHP 5 at the top of the file, but some work was done in Aug 2015 to make it PHP7 compatible including some test cases.

I'll report if I find other issues related to PHP7.  The limited testing I have done has worked so far.

**Comment by cpinfold** [comment]
Also updated the Wiki to reflect < PHP 7.0

https://github.com/eventum/eventum/wiki/Prerequisites

**Comment by glensc** [comment]
oh, i recall pear/mail lock was due some other bug. eventum abused some library internals which are no longer public in new version.

**Comment by glensc** [comment]
there's another php7 incompatibility: 6ba453463

**Comment by glensc** [comment]
@cpinfold could you review and perhaps test #236

**Comment by glensc** [comment]
fixed with #236

**Comment by laberg** [comment]
I still have this issue on only one of my servers. Even though they both have the same php version...

**Comment by glensc** [comment]
this is bug report against unsupported version. also if you have a problem, you should create a new issue, not hijack random issues you think are relevant.
