### ISSUE TITLE
Error Checking configuration email buttom

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#91]
I installed the new 3.0.5. Before i had 3.0.2 with a pop account and works fine.
But in 3.0.5 in the administration panel when i push the bottom check configuration i get and error for  undefined index for 'folder'. 
In [check_email_settings.php i commented 49 line](https://github.com/eventum/eventum/blob/v3.0.5/htdocs/manage/check_email_settings.php#L49)
#'ema_folder'   => $_POST['folder'],
and put this
'ema_folder' => isset($_POST['folder']) ? $_POST['folder'] :  '',
working fine.

I'm getting similar errors in 'associated emails' in lines [236,237,238 and 239 of class.mail_helper.php](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.mail_helper.php#L236-L239). I'm going to do the same that before. 
In all the cases eventum is downloading the emails and checking ok the connection.

Regards 
Antonio

**Comment by plindry** [comment]
I can't do that the problem is that this fields must be filled with the data of the pop account. No problem in 3.0.2

**Comment by glensc** [comment]
(updated ticket to point to sourcecode exact lines), your second comment here needs translating to English.

**Comment by glensc** [comment]
your first problem seems to came from fixes from #66 and #69.
probably easy fix.

second problem could come from anywhere [Mail_Helper::getAddressInfo](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.mail_helper.php#L221) is called from four different places:
 - [Mail_Helper::getEmailAddress](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.mail_helper.php#L260)
 - [Mail_Helper::getName](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.mail_helper.php#L277)
 - [Notification::getFixedFromHeader](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.notification.php#L189)
 - [Notification::getFixedFromHeader](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.notification.php#L193)

and those methods from even more places. 

it just means some email address that you have there, is invalid.

**Comment by glensc** [comment]
you mean you press "Test Settings" button on "Manage Email Accounts" (manage/email_accounts.php) panel?

and the error comes from popup window (manage/check_email_settings.php)?

**Comment by plindry** [comment]
Yes comes from this window

**Comment by plindry** [comment]
I fixed 236,237,238 and 239 of class.mail_helper.php. changing
#'sender_name' => $row->personal,		
				#'username' => $row->mailbox ,
				#'host' => $row->host,
				#'email' => $row->mailbox . '@' . $row->host,
				'sender_name' => isset($row->personal) ? $row->personal :  '',
                                 'username' => isset($row->mailbox) ? $row->mailbox :  '',
				'host' => isset($row->host) ? $row->host :  '',
				'email' => (isset($row->mailbox) ? $row->mailbox :  '') . '@' . (isset($row->host) ? $row->host :  ''),

**Comment by plindry** [comment]
Sorry for my English --)

**Comment by glensc** [comment]
still don't get what are you trying to fix. what is the problem description?

just hiding errors does not fix the underlying problem. for now i don't know what are you attempting to fix. of course if input is invalid the $row is also invalid.

i explained where the method is called:
https://github.com/eventum/eventum/issues/91#issuecomment-154195637

so from which code path your invalid input comes from?

perhaps add to code:
```php
$e = new Exception();
error_log($e->getTraceAsString());
```

to identify where and how invalid input comes in.

**Comment by plindry** [comment]
Ok i'll try to review the code for discover where the invalid inputs are generated.

P.D. Similar case in ../htdocs/manage/general.php lines 53,54,55,56 for undefined index that seem to have the same source.

**Comment by glensc** [comment]
plz use links to github code lines, like i modified your original submit.

**Comment by plindry** [comment]
(https://github.com/eventum/eventum/htdocs/manage/general.php#L53-L56

**Comment by glensc** [comment]
didn't you say you were on [v3.0.5](https://github.com/eventum/eventum/tree/v3.0.5)?

**Comment by plindry** [comment]
YES

**Comment by cpinfold** [comment]
I've been looking at the first error in v3.0.6 with [check_email_settings.php] (https://github.com/eventum/eventum/blob/v3.0.5/htdocs/manage/check_email_settings.php#L49)

@plindry is right, there would be a notice error due to the JS hiding the folder setting (and therefore not submitting)  I don't show that it is preventing the system from working though.  Not sure why you have your error level high enough to see this in a production environment or are you testing a development environment?  

I have fixed the first notice issue using `ifSet()` and will send in a pull request after I take a quick look at the others.

**Comment by cpinfold** [comment]
@plindry , Antonio,

I can't find the notice errors you reference in [236,237,238 and 239 of class.mail_helper.php](https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.mail_helper.php#L236-L239)

If you can tell me what page (full page name ending in .php)  and what you were doing to trigger the errors, I'll take another look.  Eg. if on a form, what content did you enter?

Craig.

**Comment by plindry** [comment]
Hy Craig, thanks for the look.
The content in this form are a lot of mails. In the test machine i use a mailbox that is receiving a copy of all mails. It seems some character or similar in fields  'sender_name' ,'email', 'host', or 'username' is generating this null. Now i'm not in my office. I'll be back on tuesday, then i'll modify the code i put before for using intead ' ' some character that i can recognice. Other option is compare with the data base.

I'll inform you.
Regards

**Comment by plindry** [comment]
I'm still receiving error from this part of code:
https://github.com/eventum/eventum/blob/v3.0.6/lib/eventum/class.mail_helper.php#L236-L239

I'm receiving: 
Notice: Undefined property: stdClass::$personal in D:\xampp\htdocs\eventum\lib\eventum\class.mail_helper.php on line 237
Notice: Undefined property: stdClass::$mailbox in D:\xampp\htdocs\eventum\lib\eventum\class.mail_helper.php on line 238
Notice: Undefined property: stdClass::$host in D:\xampp\htdocs\eventum\lib\eventum\class.mail_helper.php on line 239
Notice: Undefined property: stdClass::$mailbox in D:\xampp\htdocs\eventum\lib\eventum\class.mail_helper.php on line 240
Notice: Undefined property: stdClass::$host in D:\xampp\htdocs\eventum\lib\eventum\class.mail_helper.php on line 240

I write a workaorund with this code:

'sender_name' => isset($row->personal) ? $row->personal :  '',
'username' => isset($row->mailbox) ? $row->mailbox :  '',
'host' => isset($row->host) ? $row->host :  '',
'email' => (isset($row->mailbox) ? $row->mailbox :  '') . '@' . (isset($row->host) ? $row->host :  ''),

It's a strange character in some emails and a problem parsing it. I'm going to analize the emails and i will tell you.

**Comment by glensc** [comment]
@plindry and why you should get something else. you have not provided us any information where does the invalid input comes from. your workaround will not be accepted no matter how many times you paste it. the problem must be fixed elsewhere.

why is your [$addresslist](https://github.com/eventum/eventum/blob/v3.0.6/lib/eventum/class.mail_helper.php#L234) containing invalid data, don't know, you need to debug that yourself.

**Comment by plindry** [comment]
Glensc, i don't need that this code will be accepted. Is a workaround for me. right?
You know that over v3.0.5 release i update some files without the commits (my fault), as you remembered me in previous posts. 
I prefer starting from scracth with the new release 3.0.6 so this morning i installed and tested it. The only thing i want to say is that i have the same problem and the problem seem not to be for mixed versions of files. right?
Tomorrow i'll pretend debug in a deeper way with my clean release but i think things can be said in many ways i i have the sensation that i'm disturbing as a newbei becuase the really thing this is the first time i discover that eventum is not dead. So i'll try not to disturb..

**Comment by plindry** [comment]
Ok i check the problem viewing de data entry in eventum_support_mail table. I include the code  i was suggested. The exception is dued for a semicolon character " ; ".
The code can't deal with that. In the database de mail is from a sender that use CCO with many adressee and don´t like others know his mail (i suppose). The email server (¿?), or the code of eventum (¿?) sets "destinatarios-no-revelados: ;". In english "unrevealed addressee: ;" that is what you see in the database.

I'll continue investigating

**Comment by glensc** [comment]
i need actual data in `print_r` form to debug this, as noted in this comment, including backtrace:

https://github.com/eventum/eventum/issues/91#issuecomment-155862480

you may obfuscate sensitive information, but may not change any other bit in it.

**Comment by plindry** [comment]
¿This?

12-Nov-2015 17:40:34 Europe/Madrid] #0 ../htdocs/ev306/lib/eventum/class.mail_helper.php(289): Mail_Helper::getAddressInfo('destinatarios-n...', true)
#1 ../htdocs/ev306/lib/eventum/class.support.php(1331): Mail_Helper::getName('destinatarios-n...')
#2 ../htdocs/ev306/htdocs/emails.php(61): Support::getEmailListing(Array, 0, 'ALL')
#3 {main}

[12-Nov-2015 17:40:34 Europe/Madrid] PHP Notice:  Undefined property: stdClass::$personal in ../htdocs/ev306/lib/eventum/class.mail_helper.php on line 241

[12-Nov-2015 17:40:34 Europe/Madrid] PHP Notice:  Undefined property: stdClass::$mailbox in ../htdocs/ev306/lib/eventum/class.mail_helper.php on line 242

[12-Nov-2015 17:40:34 Europe/Madrid] PHP Notice:  Undefined property: stdClass::$host in ../htdocs/ev306/lib/eventum/class.mail_helper.php on line 242

[12-Nov-2015 17:40:34 Europe/Madrid] PHP Notice:  Undefined property: stdClass::$mailbox in ../htdocs/ev306/lib/eventum/class.mail_helper.php on line 243

[12-Nov-2015 17:40:34 Europe/Madrid] PHP Notice:  Undefined property: stdClass::$host in ../htdocs/ev306/lib/eventum/class.mail_helper.php on line 244

**Comment by glensc** [comment]
please include what command and what output, can't understand right now (edit your message)

**Comment by plindry** [comment]
The problem is when you receive a email without an adresse you have the problem. The only you see y @ from 'email' => $row->mailbox . '@' . $row->host, where $row->mailbox and $row->host are null.

**Comment by glensc** [comment]
oh, you never said you get the error from "Associate Emails" view (emails.php), i see this now from the trace.
